<?php
/**
 * This file is part of FirstTimeOnly4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 *  https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\FirstTimeOnly4\Tests\Web;


use Eccube\Tests\Web\Admin\AbstractAdminWebTestCase;

class ProductControllerTest extends AbstractAdminWebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test商品規格なしで初回購入限定項目が表示されるか()
    {
        $product = $this->createProduct(null, 0);

        $crawler = $this->client->request(
            'GET',
            $this->generateUrl('admin_product_product_edit', ['id' => $product->getId()])
        );

        self::assertContains('初回購入限定', $crawler->filter('#basicConfig')->html());
    }

    public function test商品規格ありで初回購入限定項目が表示されるか()
    {
        $product = $this->createProduct();

        $crawler = $this->client->request(
            'GET',
            $this->generateUrl("admin_product_product_class", ["id" => $product->getId()])
        );

        self::assertContains("初回購入限定", $crawler->filter("#ex-product_class")->html());
    }
}
